src/views/ApiKey.js, src/views/ChatGrupal.js, src/views/ChatIndividual.js, src/views/ErrorRutas.js, src/views/Example.js, src/views/Home.js
=> build: creation of home, chats, apikey views with demo function

src/index.js, src/router.js, src/views/ApiKey.js, src/views/ChatGrupal.js, src/views/ChatIndividual.js, src/views/ErrorRutas.js, src/views/Home.js
-  Closes #8 
-  Closes #9 
-  Closes #10 
-  Closes #11 
-  Closes #12
=> build: router functions, load main page

test/router.spec.js
=> test: unit test renderView #13

src/lib/dataFunctions.js
=> update: dataFunctions #15

src/style.css
=> update: style.css #18

test/data.js, test/dataFunctions.spec.js
=> update: test files data.js and dataFunctions.specs.js #16

src/components/Header.js, src/index.html, src/index.js, src/router.js, src/views/Home.js
- Creamos el header según el proyecto anterior. 
- Tenemos dudas sobre qué componente debe ser "root" y qué componente debe retornar la vista home.
- Modifica el issue #17
=> feature: header component #17

src/components/Cards.js, src/components/Footer.js, src/data/dataset.js, src/views/Home.js
=> feature: components footer, main.js and functions #17

src/components/Cards.js, src/index.html, src/views/Home.js
=> fix: home view and add render metrics component

src/components/Header.js, src/components/Nav.js, src/components/header.css, src/components/nav.css, src/index.html, src/styles/style.css
=> Styles css view

src/styles/apiKey.css, src/styles/style.css, src/views/ApiKey.js
=> feature: view apikey and styles #47

src/lib/apiKey.js, src/views/ApiKey.js, test/apiKey.spec.js
=> setup: files for apiKey functions and tests

src/lib/apiKey.js, src/lib/styleUtils.js, src/lib/viewUtils.js, src/styles/apiKey.css, src/styles/style.css, src/views/ApiKey.js, src/views/ChatGrupal.js, src/views/ChatIndividual.js, src/views/ErrorRutas.js, src/views/Home.js
=> feature: apikey functions and styles 

package-lock.json, package.json, src/components/ChatIndividual.js, src/lib/openAIApi.js
- It develops #50 
- It develops #54
=> setup: openAIApi file

src/views/ChatGroup.js, src/views/NotFound.js
=> Chore: estructuras de la vista chat group y notfound

src/components/ChatIndividual.js, src/lib/openAIApi.js
=> refactor: Remove unnecessary chat message and update chat history initialization

test/apiKey.spec.js, test/openAIApi.spec.js
=> test: OpenAI

.eslintrc, test/openAIApi.spec.js
- Ajusté el archivo eslint para que reconozca `global` (objeto que representa el espacio de nombres global).
- Añadí un caso para probar el caso `default` del switch, con ello hay cobertura del 100%
- It fixes #74
=> fix: openAI test

test/apiKey.spec.js
- Añadí 2 casos con mocks para probar las dependencias de nuestras funciones
=> feature: adding tests with mocks

src/index.js, src/router.js, src/vercel.json
- @LicetLemus añadí un archivo vercel.json para redirigir al path correcto en la recarga, así no nos muestra esa pantalla 404.
- En router.js, por qué tenemos esta línea de código del 40-43? le añadí crear el root si no había, pero no recuerdo por qué la tenemos, creo que la podríamos borrar . Comentada el proyecto funciona.Dale una chequeadita plis. 👀 
```
if (!ROOT) {
//return;
setRootEl(document.querySelector(".root"));
}
```
=> fix: error in reload on deployed web
